- hosts: all
  tasks:
  - name: Log into DockerHub
    docker_login:
      username: shirzadi
      password: "{{ password }}"
      email: ehsan.shirzadi@gmail.com
    become: yes
    vars:
      ansible_python_interpreter: /bin/python3    
