---
- hosts: all
  become: yes
  tasks:
  - name: Add traefik repository
    shell: helm repo add traefik https://helm.traefik.io/traefik
  - name: Install Traefik using helm
    shell: helm install traefik/traefik --set service.type=NodePort
