- name: Join a worker
  hosts: all 
  become: yes
  tasks:
  - name: Copying token to master nodes
    copy: src={{ TEMP_DIR }}/joinmaster.sh dest=joinmaster.sh
  - name: join
    shell: sh joinmaster.sh
