- name: Join a worker
  hosts: all 
  become: yes
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ TEMP_DIR }}/joinworker.sh dest=joinworker.sh
  - name: join
    shell: sh joinworker.sh
