---
- hosts: all
  become: yes
  tasks:
  - name: gettin admin password
    shell: kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}"  --kubeconfig /etc/kubernetes/admin.conf | base64 --decode && echo
